# WAP to input eight numbers from the user and display all the unique numbers(once)
S = set()
n = input("Enter numbers :  ")
S.add(int(n))
n = input("Enter numbers :  ")
S.add(int(n))
n = input("Enter numbers :  ")
S.add(int(n))
n = input("Enter numbers :  ")
S.add(int(n))
n = input("Enter numbers :  ")
S.add(int(n))
n = input("Enter numbers :  ")
S.add(int(n))
n = input("Enter numbers :  ")
S.add(int(n))

print(S) 
